# Generated by Django 4.2.30 on 2026-05-30 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.PositiveSmallIntegerField(help_text='e.g. 1 for Year 1')),
                ('research_progress', models.TextField(help_text='Summarise research progress, achievements and milestones reached this year.')),
                ('training_activities', models.TextField(help_text='List conferences attended, workshops, seminars, and skills training.')),
                ('publications', models.TextField(blank=True, help_text='List any publications, papers submitted, or conference presentations.')),
                ('issues_concerns', models.TextField(blank=True, help_text='Any challenges, concerns, or welfare issues to raise.')),
                ('next_year_plan', models.TextField(help_text='Objectives and planned activities for the next 12 months.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (In Progress)'), ('SUBMITTED', 'Submitted - Awaiting Supervisor'), ('SUPERVISOR_ENDORSED', 'Supervisor Endorsed - Awaiting Coordinator'), ('COORDINATOR_APPROVED', 'Approved - Progression Cleared'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=25)),
                ('progression_cleared', models.BooleanField(default=False, help_text='Set to True only when Coordinator approves. Gates next-semester registration.')),
                ('supervisor_comments', models.TextField(blank=True)),
                ('supervisor_endorsed_at', models.DateTimeField(blank=True, null=True)),
                ('coordinator_comments', models.TextField(blank=True)),
                ('coordinator_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_aprs', to='accounts.adminprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apr_reports', to='courses.academicsession')),
                ('student', models.ForeignKey(limit_choices_to={'programme': 'PHD'}, on_delete=django.db.models.deletion.CASCADE, related_name='annual_reports', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Annual Progress Report',
                'verbose_name_plural': 'Annual Progress Reports',
                'ordering': ['-session__start_date'],
                'unique_together': {('student', 'session')},
            },
        ),
    ]
