# Generated by Django 4.2.30 on 2026-05-30 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2024/2025', max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Online (Paystack)'), ('MANUAL', 'Manual (Bank Receipt Upload)')], max_length=6)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=8)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paystack_payment_id', models.CharField(blank=True, max_length=100)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to=fees.models.receipt_upload_path)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fee_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payments',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
